name: Checkov

on:
    push:
      branches: [ "main" ]
    pull_request:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
  checkov:
    name: "Checkov"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Checkov static analysis
        id: static-analysis
        uses: bridgecrewio/checkov-action@8e27188287937dbe47f6ef7d02a7256f60fc440e # v12.2486.0
        with:
          directory: .
          framework: terraform
          hard_fail_on: CRITICAL
          skip_check: CKV_TF_1
          output_format: cli
