name: Terrascan

on:
    push:
      branches: [ "main" ]
    pull_request:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
  checkov:
    name: "Terrascan"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Run Terrascan
        id: terrascan
        uses: tenable/terrascan-action@3a6e87da8e244513bd77b631e624552643f794c6 # v1.4.1
        with:
          iac_type: 'terraform'
          iac_version: 'v14'
          policy_type: 'aws'
          only_warn: true
          sarif_upload: true

      - name: CodeQL upload Terrascan results SARIF
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: terrascan.sarif
