name: Terrascan

on:
    push:
      branches: [ "main" ]
    pull_request:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
  checkov:
    name: "Terrascan"
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Run Terrascan
        id: terrascan
        uses: tenable/terrascan-action@dd7e921056c6f25b25bff3cf791e063ed7fc3a78 # v1.5.0
        with:
          iac_type: 'terraform'
          iac_version: 'v14'
          policy_type: 'aws'
          only_warn: true
          sarif_upload: true

      - name: CodeQL upload Terrascan results SARIF
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: terrascan.sarif
